---
- name: Show Run
  hosts: 10.1.16.203
  gather_facts: no
  connection: network_cli
  remote_user: admin
  become: yes
  become_method: enable
  become_user: admin

  tasks:
    - name: Show Run
        ios_command:
          commands: sh Run
        register: show run